import jsPDF from 'jspdf';
import type { CaseData, CaseTask } from '../types.ts';

export function generateCaseSummaryPdf(
  caseData: CaseData,
  eventTitle: string,
  clientName: string,
): void {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const checkSpace = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const drawLine = () => {
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
  };

  // Header
  doc.setFillColor(30, 30, 50);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Case Summary Report', margin, 18);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by Spherical Assistant | SphereLabs`, margin, 28);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, 34);

  y = 52;
  doc.setTextColor(40, 40, 40);

  // Case overview
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Case Overview', margin, y);
  y += 8;
  drawLine();

  doc.setFontSize(10);
  const fields: [string, string][] = [
    ['Case', eventTitle],
    ['Client', clientName],
    ['Industry', caseData.industry],
    ['Documents', `${caseData.documents.length}`],
    ['Last Updated', new Date(caseData.updatedAt).toLocaleDateString()],
  ];
  for (const [label, value] of fields) {
    checkSpace(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, margin + 45, y);
    y += 7;
  }
  y += 4;

  // Tasks
  const completed = caseData.tasks.filter((t) => t.done);
  const pending = caseData.tasks.filter((t) => !t.done);

  if (caseData.tasks.length > 0) {
    checkSpace(30);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Tasks (${completed.length}/${caseData.tasks.length} complete)`, margin, y);
    y += 8;
    drawLine();

    doc.setFontSize(10);
    const renderTasks = (tasks: CaseTask[], prefix: string) => {
      for (const task of tasks) {
        const lines = doc.splitTextToSize(`${prefix} ${task.label}`, maxWidth - 4);
        checkSpace(lines.length * 5 + 3);
        doc.setFont('helvetica', 'normal');
        doc.text(lines, margin + 4, y);
        y += lines.length * 5 + 2;
      }
    };

    if (pending.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.text('Pending:', margin, y);
      y += 6;
      renderTasks(pending, '☐');
      y += 2;
    }
    if (completed.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.text('Completed:', margin, y);
      y += 6;
      renderTasks(completed, '☑');
    }
    y += 4;
  }

  // Documents
  if (caseData.documents.length > 0) {
    checkSpace(30);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Documents on File', margin, y);
    y += 8;
    drawLine();

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    for (const d of caseData.documents) {
      checkSpace(10);
      doc.text(`• ${d.name} (${d.category}) — ${new Date(d.uploadedAt).toLocaleDateString()}`, margin + 4, y);
      y += 6;
    }
    y += 4;
  }

  // Activity log (last 20)
  const recentActivity = caseData.activityLog.slice(0, 20);
  if (recentActivity.length > 0) {
    checkSpace(30);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Recent Activity', margin, y);
    y += 8;
    drawLine();

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    for (const entry of recentActivity) {
      const lines = doc.splitTextToSize(
        `${new Date(entry.timestamp).toLocaleString()} — ${entry.label}`,
        maxWidth - 4,
      );
      checkSpace(lines.length * 4 + 3);
      doc.text(lines, margin + 4, y);
      y += lines.length * 4 + 2;
    }
  }

  // Footer on every page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'Confidential — Generated by Spherical Assistant | SphereLabs',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' },
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - margin,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'right' },
    );
  }

  const filename = `case-summary-${clientName.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`;
  doc.save(filename);
}
